In [ ]:
#Q1
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr=np.flip(arr)
print(reversed_arr)

[5 4 6 3 2 1]


In [ ]:
#Q2
#method-1
import numpy as np
array1=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array=array1.flatten()
print(flattened_array)
#method-2
import numpy as np
array1=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array=array1.ravel()
print(flattened_array)
#flatten:changes made to flattened array will not be copied to original arr
#ravel:changes made to raveled array will be copied to original array

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
#Q3
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
element_wise_comparison = arr1 == arr2
print("Element wise comparison:\n",element_wise_comparison)
overall_comparison = np.array_equal(arr1, arr2)
print("overall array comparison:\n",overall_comparison)


Element wise comparison:
 [[ True  True]
 [ True  True]]
overall array comparison:
 True


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent_val=np.bincount(x).argmax()
most_frequent_val_indices=np.where(x==most_frequent_val)
print("Most frequent occuring values:",most_frequent_val)
print("Indices:",most_frequent_val_indices)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3 ])
counts_y = np.bincount(y)
most_freq_y = np.where(counts_y == counts_y.max())[0]

for value in most_freq_y:
    indices_y = np.where(y == value)[0]
    print(f"Array y: Most frequent value = {value}, Indices = {indices_y.tolist()}")

Most frequent occuring values: 1
Indices: (array([0, 5, 7, 8, 9]),)
Array y: Most frequent value = 1, Indices = [0, 1, 2]
Array y: Most frequent value = 3, Indices = [4, 8, 9]


In [ ]:
#Q5
import numpy as np
gfg=np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_of_elements=np.sum(gfg)
print("total sum:",sum_of_elements)
row_sum=np.sum(gfg,axis=1)
print("sum of row elemnts:\n",row_sum)
col_sum=np.sum(gfg,axis=0)
print("sum of column elemnts:\n",col_sum)

total sum: 45
sum of row elemnts:
 [[14]
 [16]
 [15]]
sum of column elemnts:
 [[20  9 16]]


In [ ]:
#Q6
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
sum_diagonal=np.trace(n_array)
print("Diagonal sum:",sum_diagonal)


Diagonal sum: 176
